packages:
  - '*/src'

onlyBuiltDependencies:
  - esbuild

catalog:
  '@aotoki/slidev-theme-terraforming': ^0.4.3
  '@slidev/cli': ^52.14.2
  '@slidev/theme-default': latest
  '@slidev/theme-seriph': latest
